swagger: '2.0'
info:
  description: HackerNews
  version: 1.0.0
  title: HackerNews
  termsOfService: 'https://news.ycombinator.com/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:3000'
basePath: /api
tags:
  - name: posts
    description: Publicaciones
  - name: comments
    description: Comentarios
schemes:
  - "http"
paths:
  /posts:
    get:
      tags:
        - Index
      summary: Get all the URLs
      description: ''
      responses:
        '200':
          description: Get all URLs
          
  /post_create:
    post:
      tags:
        - post
      summary: "Add a new post"
      description: ""
      consumes:
      - "application/json"
      - "application/x-www-form-urlencoded"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "title"
        in: "formData"
        description: "Titol del post"
        required: true
        type: "string"
      - name: "tipo"
        in: "formData"
        description: "Tipus del post"
        required: true
        type: "array"
        items:
          type: "string"
          enum:
          - "URL"
          - "ask"
          default: "URL"
        collectionFormat: "multi"
      - name: "content"
        in: "formData"
        description: "URL or Text"
        required: true
        type: "string"
      responses:
         405:
          description: "Invalid input"
  /ask:
    get:
      tags:
        - ask
      summary: Get all the Asks
      description: ''
      responses:
        '200':
          description: Get all Asks
          schema:
            $ref: '#/definitions/Post'
  /comments:
    post:
      description: |
        Crea un nuevo comentario para un post
      parameters:
        - name: comment
          in: formData
          description: Texto del comentario
          required: true
          type: string
        - name: user_id
          in: formData
          description: Identificador del usuario
          required: true
          type: number
        - name: post_id
          in: formData
          description: Identificador del post
          required: true
          type: number
      responses:
        '200':
          description: Succesfully created
          schema:
            $ref: '#/definitions/Comment'
        '400':
          description: No existe el comentario
          schema:
            type: object
            properties:
              error:
                type: string
        '401':
          description: No autoritzat
          schema:
            type: object
            properties:
              error:
                type: string
                
  /reply:
    post:
      description: |
        Crea un nuevo reply para un comentario
      parameters:
        - name: comment
          in: formData
          description: Texto del comentario
          required: true
          type: string
        - name: user_id
          in: formData
          description: Identificador del usuario
          required: true
          type: number
        - name: post_id
          in: formData
          description: Identificador del post
          required: true
          type: number
        - name: parent_id
          in: formData
          description: Identificador del comentario que cuelga
          required: true
          type: number
      responses:
        '200':
          description: Succesfully created
          schema:
            $ref: '#/definitions/Comment'
        '400':
          description: No existe el comentario
          schema:
            type: object
            properties:
              error:
                type: string
        '401':
          description: No autoritzat
          schema:
            type: object
            properties:
              error:
                type: string
  
  /deleteComment:
    delete:
      description: |
        Crea un nuevo reply para un comentario
      parameters:
        - name: id
          in: formData
          description: Identificador del comentario
          required: true
          type: number
      responses:
        '200':
          description: Succesfully created
          schema:
            $ref: '#/definitions/Comment'
        '400':
          description: No existe el comentario
          schema:
            type: object
            properties:
              error:
                type: string
        '401':
          description: No autoritzat
          schema:
            type: object
            properties:
              error:
                type: string              
                
  /upvote:
    post:
      description: |
        Vota un post
      parameters:
        - name: user_id
          in: formData
          description: Identificador del usuario
          required: true
          type: number
        - name: post_id
          in: formData
          description: Identificador del post
          required: true
          type: number
      responses:
        '200':
          description: Succesfully upvoted
          schema:
            $ref: '#/definitions/up_vote'
        '400':
          description: No existe el post
          schema:
            type: object
            properties:
              error:
                type: string
        '401':
          description: No autoritzat
          schema:
            type: object
            properties:
              error:
                type: string
      
definitions:
  Post:
    type: object
    required:
    - "title"
    - "tipo"
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      url:
        type: string
      text:
        type: string
      user_id:
        type: integer
        format: int64
      created_at:
        type: string
        format: datetime
      updated_at:
        type: string
        format: datetime
      tipo:
        type: string
      votes:
        type: integer
        format: int64
      nComments:
        type: integer
        format: int64
      upvotes_count:
        type: integer
        format: int64
    xml:
      name: Post
  Comment:
    type: object
    properties:
      id:
        type: integer
        format: int64
      text:
        type: string
      votes:
        type: integer
        format: int64
      parent_id:
        type: integer
        format: int64
      created_at:
        type: string
        format: datetime
      updated_at:
        type: string
        format: datetime
      post_id:
        type: integer
        format: int64
      user_id:
        type: integer
        format: int64
      tipus:
        type: string
    xml:
      name: Comment
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
  
